openapi: "3.0.0"
info:
  title: Sample API
  version: 1.0.0
paths:
  /users:
    get:
      summary: Get a list of users
      responses:
        '200':
          description: OK
    post:
      summary: Add a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        '201':
          description: Created
  /users/{userId}:
      get:
        summary: Get a user by ID
        parameters:
          - name: userId
            in: path
            required: true
            description: ID of the user to retrieve
            schema:
              type: integer
        responses:
          '200':
            description: OK
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        email:
          type: string
