openapi: 3.0.0
info:
  title: Sample API
  version: 1.0.0
servers:
- url: /
paths:
  /users:
    get:
      responses:
        "200":
          description: OK
      summary: Get a list of users
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        "201":
          description: Created
      summary: Add a new user
  /users/{userId}:
    get:
      parameters:
      - description: ID of the user to retrieve
        explode: false
        in: path
        name: userId
        required: true
        schema:
          type: integer
        style: simple
      responses:
        "200":
          description: OK
      summary: Get a user by ID
components:
  schemas:
    User:
      example:
        name: name
        id: 0
        email: email
      properties:
        id:
          type: integer
        name:
          type: string
        email:
          type: string
      type: object
